config/routes.rb
Rails.application.routes.draw do
  resources :classrooms, only: [:index, :new, :create, :destroy]
  resources :courses
  resources :students

  root 'students#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student, presence: true
  validates :course, presence: true

  validate :student_already_registered

  before_create :set_entry_at

  def set_entry_at
  	self.entry_at = Time.zone.now  	
  end

  def student_already_registered
  	if Classroom.find_by(student: self.student, course: self.course)
  		errors.add(:course_id, I18n.t(:already_registered, scope: "activerecord.errors.models.classroom.attributes.course"))
  	end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  has_many :students, through: :classrooms

	validates :name, presence: true
	validates :description, presence: true
	validates :status, presence: true
	validates_inclusion_of :status, :in => [0,1]

  COURSE_STATUSES = {
  	0 => :inactive,
    1 => :active
  }

  def status_str
    I18n.t(COURSE_STATUSES[self.status], scope: "course_statuses")
  end

  def self.statuses_collection
    statuses_collection = []

    COURSE_STATUSES.each_pair do |key, value|
        statuses_collection << [I18n.t(value, scope: "course_statuses"), key]
    end

    return statuses_collection
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  has_many :courses, through: :classrooms

	validates :name, presence: true
	validates :register_number, presence: true, uniqueness: true
	validates :status, presence: true
	validates_inclusion_of :status, :in => [0,1]

  STUDENT_STATUSES = {
  	0 => :inactive,
    1 => :active
  }

  def status_str
    I18n.t(STUDENT_STATUSES[self.status], scope: "student_statuses")
  end

  def self.statuses_collection
    statuses_collection = []

    STUDENT_STATUSES.each_pair do |key, value|
        statuses_collection << [I18n.t(value, scope: "student_statuses"), key]
    end

    return statuses_collection
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_collections, only: [:new]

  def index
    @classrooms = Classroom.all
  end

  def new
    @classroom = Classroom.new
  end

  def create
  	@classroom = Classroom.new(classroom_params)

  	respond_to do |format|
  		if @classroom.save
        format.html { redirect_to classrooms_path, notice: I18n.t(:created, model: I18n.t(:classroom, scope: "activerecord.models")) }
      else
        format.html { render :new }
      end
  	end
  end

  def destroy
  	@classroom = Classroom.find(params[:id])
  	@classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: I18n.t(:deleted, model: I18n.t(:student, scope: "activerecord.models")) }
    end
  end

  private
  	def classroom_params
      params.require(:classroom).permit(:student_id, :course_id)
    end

    def set_collections
      @students = Student.all
      @courses = Course.all
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :set_collections, only: [:new, :edit]

  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /courses/1
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: I18n.t(:created, model: I18n.t(:course, scope: "activerecord.models")) }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: I18n.t(:updated, model: I18n.t(:course, scope: "activerecord.models")) }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: I18n.t(:deleted, model: I18n.t(:course, scope: "activerecord.models")) }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :status)
    end

    def set_collections
      @course_statuses = Course.statuses_collection
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_collections, only: [:new, :edit]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: I18n.t(:created, model: I18n.t(:student, scope: "activerecord.models")) }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: I18n.t(:updated, model: I18n.t(:student, scope: "activerecord.models")) }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: I18n.t(:deleted, model: I18n.t(:student, scope: "activerecord.models")) }
      format.json { head :no_content }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end

    def set_collections
      @student_statuses = Student.statuses_collection
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/classrooms/index.html.erb
<h1 class="page-header">
  <%= t(:list, scope: "commons.unisex", model: t(:classroom, scope: "activerecord.models").pluralize) %>
  <small><%= link_to t(:new, scope: "commons.female", model: t(:classroom, scope: "activerecord.models")), new_classroom_path, class: "btn btn-primary pull-right" %></small>
</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t(:student_id, scope: "activerecord.attributes.classroom") %></th>
      <th><%= t(:course_id, scope: "activerecord.attributes.classroom") %></th>
      <th><%= t(:entry_at, scope: "activerecord.attributes.classroom") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.student.name %></td>
        <td><%= classroom.course.name %></td>
        <td><%= l classroom.entry_at %></td>
        <td><%= link_to t(:show), classroom %></td>
        <td><%= link_to t(:destroy), classroom, method: :delete, data: { confirm: t(:are_you_sure?) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/classrooms/new.html.erb
<h1 class="page-header">
  <%= t(:new, scope: "commons.female", model: t(:classroom, scope: 'activerecord.models')) %>
  <small><%= link_to t(:back), classrooms_path, class: "btn btn-primary pull-right" %></small>
</h1>

<%= simple_form_for(@classroom, html: {class: 'form' }) do |f| %>
  <% if @classroom.errors.any? %>
    <div class="error_explanation">
      <h4><%= pluralize(@classroom.errors.count, t(:error_found)) %>:</h4>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :student_id, collection: @students, as: :select, prompt: I18n.t(:student_id, scope: "placeholders.classroom") %>
  <%= f.input :course_id, collection: @courses, as: :select, prompt: I18n.t(:course_id, scope: "placeholders.classroom") %>

  <%= f.button :submit, class: "btn-default" %>
<% end %>

app/views/courses/_form.html.erb
<%= simple_form_for(@course, html: {class: 'form' }) do |f| %>
  <% if @course.errors.any? %>
    <div class="error_explanation">
      <h4><%= pluralize(@course.errors.count, t(:error_found)) %>:</h4>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, placeholder: I18n.t(:name, scope: "placeholders.course"), input_html: { pattern: "[a-zA-ZÀ-ú -]+" } %>
  <%= f.input :description, placeholder: I18n.t(:description, scope: "placeholders.course") %>
  <%= f.input :status, collection: @course_statuses, as: :select, prompt: I18n.t(:choose_one), selected: (@course.status ? @course.status : 1) %>

  <%= f.button :submit, class: "btn-default" %>
<% end %>

app/views/courses/edit.html.erb
<h1 class="page-header">
	<%= t(:editing, scope: "commons.unisex", model: t(:course, scope: "activerecord.models")) %>
	<%= link_to t(:show), @course, class: "btn btn-primary pull-right" %><%= link_to t(:back), courses_path, class: "btn btn-primary pull-right margin-right-10" %>
</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1 class="page-header">
  <%= t(:list, scope: "commons.unisex", model: t(:course, scope: "activerecord.models").pluralize) %>
  <%= link_to t(:new, scope: "commons.male", model: t(:course, scope: "activerecord.models")), new_course_path, class: "btn btn-primary pull-right" %>
</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t(:name, scope: "activerecord.attributes.course") %></th>
      <th><%= t(:description, scope: "activerecord.attributes.course") %></th>
      <th><%= t(:status, scope: "activerecord.attributes.course") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><span class="label label-<%= (course.status == 1 ? "success" : "danger") %>"><%= course.status_str %></span></td>
        <td><%= link_to t(:show), course %></td>
        <td><%= link_to t(:edit), edit_course_path(course) %></td>
        <td><%= link_to t(:destroy), course, method: :delete, data: { confirm: t(:are_you_sure?) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1 class="page-header">
	<%= t(:new, scope: "commons.male", model: t(:course, scope: 'activerecord.models')) %>
	<%= link_to t(:back), courses_path, class: "btn btn-primary pull-right" %>
</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1 class="page-header">
	<%= t(:view, scope: "commons.unisex", model: t(:course, scope: "activerecord.models")) %>
	<%= link_to t(:edit, scope: "commons.unisex", model: t(:course, scope: "activerecord.models")), edit_course_path(@course), class: "btn btn-primary pull-right" %>
	<%= link_to t(:back), courses_path, class: "btn btn-primary pull-right margin-right-10" %>
</h1>

<h3>
	<small><%= t(:name, scope: "activerecord.attributes.course") %></small><br>
	<%= @course.name %>
</h3>
<h3>
	<small><%= t(:description, scope: "activerecord.attributes.course") %></small><br>
	<%= @course.description %>
</h3>
<h3>
	<small><%= t(:status, scope: "activerecord.attributes.course") %></small><br>
	<span class="label label-<%= (@course.status == 1 ? "success" : "danger") %>"><%= @course.status_str %></span>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RepenseProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Repense Project</a>
      </div>
    </div>
  </nav>

	<div class="container-fluid" id="main-content">
		<div class="row">
			<div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li class="<%= "active" if params[:controller] == "students" %>">
            <%= link_to t(:student, scope: "activerecord.models").pluralize, students_url %>
          </li>
          <li class="<%= "active" if params[:controller] == "courses" %>">
            <%= link_to t(:course, scope: "activerecord.models").pluralize, courses_url %>
          </li>
          <li class="<%= "active" if params[:controller] == "classrooms" %>">
            <%= link_to t(:classroom, scope: "activerecord.models").pluralize, classrooms_url %>
          </li>
        </ul>
      </div>

      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <% if notice %>
          <p id="notice" class="bg-info"><%= notice %></p>
        <% end -%>
				<%= yield %>
      </div>
		</div>
	</div>

</body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for(@student, html: {class: 'form' }) do |f| %>
  <% if @student.errors.any? %>
    <div class="error_explanation">
      <h4><%= pluralize(@student.errors.count, t(:error_found)) %>:</h4>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, placeholder: I18n.t(:name, scope: "placeholders.student"), input_html: { pattern: "[a-zA-ZÀ-ú -]+" } %>
  <%= f.input :register_number, placeholder: I18n.t(:register_number, scope: "placeholders.student"), input_html: { pattern: "[0-9]+" } %>
  <%= f.input :status, collection: @student_statuses, as: :select, prompt: I18n.t(:choose_one), selected: (@student.status ? @student.status : 1) %>

  <%= f.button :submit, class: "btn-default" %>
<% end %>

app/views/students/edit.html.erb
<h1 class="page-header">
	<%= t(:editing, scope: "commons.unisex", model: t(:student, scope: "activerecord.models")) %>

	<%= link_to t(:show), @student, class: "btn btn-primary pull-right" %>
	<%= link_to t(:back), students_path, class: "btn btn-primary pull-right margin-right-10" %>
</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h1 class="page-header">
  <%= t(:list, scope: "commons.unisex", model: t(:student, scope: "activerecord.models").pluralize) %>

  <%= link_to t(:new, scope: "commons.male", model: t(:student, scope: "activerecord.models")), new_student_path, class: "btn btn-primary pull-right" %>
</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t(:name, scope: "activerecord.attributes.student") %></th>
      <th><%= t(:register_number, scope: "activerecord.attributes.student") %></th>
      <th><%= t(:status, scope: "activerecord.attributes.student") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.register_number %></td>
        <td><span class="label label-<%= (student.status == 1 ? "success" : "danger") %>"><%= student.status_str %></span></td>
        <td><%= link_to t(:show), student %></td>
        <td><%= link_to t(:edit), edit_student_path(student) %></td>
        <td><%= link_to t(:destroy), student, method: :delete, data: { confirm: t(:are_you_sure?) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1 class="page-header">
	<%= t(:new, scope: "commons.male", model: t(:student, scope: 'activerecord.models')) %>
	<%= link_to t(:back), students_path, class: "btn btn-primary pull-right" %>
</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<h1 class="page-header">
	<%= t(:view, scope: "commons.unisex", model: t(:course, scope: "activerecord.models")) %>
	<%= link_to t(:edit, scope: "commons.unisex", model: t(:student, scope: "activerecord.models")), edit_student_path(@student), class: "btn btn-primary pull-right" %>
	<%= link_to t(:back), students_path, class: "btn btn-primary pull-right margin-right-10" %>
</h1>

<h3>
	<small><%= t(:name, scope: "activerecord.attributes.student") %></small><br>
	<%= @student.name %>
</h3>
<h3>
	<small><%= t(:register_number, scope: "activerecord.attributes.student") %></small><br>
	<%= @student.register_number %>
</h3>
<h3>
	<small><%= t(:status, scope: "activerecord.attributes.student") %></small><br>
	<span class="label label-<%= (@student.status == 1 ? "success" : "danger") %>"><%= @student.status_str %></span>
</h3>